x-registry-auth:

  registry.docker.io:
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}

services:

  backend:
    container_name: backend
    build: ./serj-back
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
      - rabbitmq
  
  # consumer:
  #   container_name: consumer
  #   build: ./serj-consumer
  #   restart: unless-stopped
  #   env_file: .env
  #   volumes:
  #     - consumer:/var/lib/queue-consumer/logs
  #   depends_on:
  #     - backend

  frontend:
    container_name: frontend
    build: ./serj-front
    restart: unless-stopped
    expose:
      - 3000
    command: serve -s /usr/src/app/build -l 3000
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-www:/var/www/certbot/:ro
      - certbot-conf:/etc/letsencrypt/:ro
    depends_on:
      - frontend
      - drone_server
    # TODO: make cron to auto update 
    # Перезапустит nginx контейнер каждые 24 часа и подгрузит новые сертификаты, если есть 
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!};' nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    build: ./certbot_m
    restart: unless-stopped
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - certbot-conf:/etc/letsencrypt/:rw
    depends_on:
      - nginx

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: unless-stopped
    env_file: .env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432 # Do not change
    volumes:
      - pgdata:/var/lib/postgresql/data
    # TODO: Add healthcheck

  celery_worker:
    build: ./serj-back
    container_name: celery_worker
    restart: unless-stopped
    command: celery -A celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - db
      - rabbitmq
      - selenium
    environment:
      SELENIUM_HOST: selenium
    volumes:
      - ./serj-back:/app

  celery_beat:
    build: ./serj-back
    container_name: celery_beat
    command: celery -A celery_app beat --loglevel=info
    restart: unless-stopped
    env_file: .env
    depends_on:
      - backend
      - rabbitmq
      - db
    volumes:
      - ./serj-back:/app

  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium
    ports:
      - "4444:4444"
  
  tgbot:
    container_name: tgbot
    build: ./serj-bot
    restart: unless-stopped
    env_file: .env
  
  drone_server:
    container_name: drone_server
    image: drone/drone:2.26-linux-amd64
    restart: unless-stopped
    expose:
      - 80 # Drone is hardcoded to 80, no way to change
    environment:
      DRONE_GITHUB_CLIENT_ID:     "${DRONE_GITHUB_CLIENT_ID}"
      DRONE_GITHUB_CLIENT_SECRET: "${DRONE_GITHUB_CLIENT_SECRET}"
      DRONE_RPC_SECRET:   "${DRONE_RPC_SECRET}"
      DRONE_SERVER_HOST:  "${DRONE_SERVER_HOST}"
      DRONE_SERVER_PROTO: "${DRONE_SERVER_PROTO}"
    volumes:
      - /var/lib/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  rabbitmq: {}
  pgdata: {}
  # consumer: {}
  certbot-www: {}
  certbot-conf: {}